create table public.entries (
  id bigint generated by default as identity primary key,
  title text not null,
  category text not null,
  amount numeric(12, 2) not null check (amount > 0),
  type text not null check (type in ('income', 'expense')),
  entry_date date not null default current_date,
  created_at timestamptz not null default now()
);

create table public.savings (
  month_key text not null check (month_key ~ '^[0-9]{4}-[0-9]{2}$'),
  amount numeric(12, 2) not null check (amount >= 0),
  updated_at timestamptz not null default now(),
  primary key (month_key)
);

alter table public.entries enable row level security;
alter table public.savings enable row level security;

create policy "Public app can manage entries"
  on public.entries for all
  using (true)
  with check (true);

create policy "Public app can manage savings"
  on public.savings for all
  using (true)
  with check (true);

alter table public.entries replica identity full;
alter table public.savings replica identity full;
alter publication supabase_realtime add table public.entries, public.savings;
